# Force main Steam window to tile
windowrule = tile on, match:class steam 

# Force all other Steam dialogs (friends, chat, settings, etc.) to float
# windowrulev2 = float, class:^(steam)$
windowrule = float on match:class:^(steam)$

#Games
windowrule = tile on match:class:^(PGA)$
windowrule = tile on match:class:^(steam_app_12200)$
#Red Dead
windowrule = fullscreen on match:class steam_app_1174180
#Batman Arkham Asylum
windowrule = fullscreen on match:class steam_app_35140
